language: node_js
node_js:
 - "node"
before_install:
 - npm install -g yarn@0.27.5
 - yarn --version
 - npm install -g sequelize-cli
 - npm install -g standard
 - npm install -g snazzy
 - psql -c 'create database node_ddd_test;' -U postgres
cache: yarn
services:
  - postgresql
install:
 - yarn
