language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
 - "node"
 before_install:
 - npm install -g yarn@0.27.5
 - yarn --version
 - npm install -g sequelize-cli
 - npm install -g standard@10.0.3
 - npm install -g babel-eslint@8.0.3
 - npm install -g snazzy
 - psql -c 'create database node_ddd_test;' -U postgres
after_script:
 - npm run coveralls
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
services:
  - postgresql
